version: '3.8'

services:
  leshabitues_database:
    container_name: leshabitues_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
#TODO  CD_DEPLOY_PASSWORD  
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: leshabitues_api
#TODO  CD_DEPLOY_PASSWORD       
      MYSQL_USER: leshabitues
      MYSQL_PASSWORD: secret
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  leshabitues_php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/leshabitues_api
    depends_on:
      - leshabitues_database
  leshabitues_nginx:
    container_name: leshabitues_api
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/leshabitues_api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - leshabitues_database